---
development:
  cloud_name: dh8ftqx9d
  api_key: '577972361557922'
  api_secret: ByZ8ETZX0U3MUsoDumB9GJ41quI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dh8ftqx9d
  api_key: '577972361557922'
  api_secret: ByZ8ETZX0U3MUsoDumB9GJ41quI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dh8ftqx9d
  api_key: '577972361557922'
  api_secret: ByZ8ETZX0U3MUsoDumB9GJ41quI
  enhance_image_tag: true
  static_file_support: false
